### PR TITLE
September Data — thanks Lloyd!

### PR DESCRIPTION
**Pull request by lloydjatkinson**
In an effort to deal with benchmarks failing due to various timeouts, runtime errors, and other issues, I ran this months benchmark in Azure. I picked US East region which I believe is similar to where GitHub Actions are run from. If all of the results are radically different then it may not be a good idea to include this dataset for consistency reasons - or use this approach all the time going forward.

### CODE REVIEW

**Comment by mandar1jn** [comment]
There seem to be some issues with the leaderboard positions when going to the lowest entries. For example, isdin is 439, by when expanding data the rank says 447

**Comment by lloydjatkinson** [comment]
I don't know what that could be other than the blacklist of slow sites that is updated occasionally. Perhaps the rank logic doesn't take them into account. It would also need to take into account sites that were not filtered out but now are.

Unrelated to this PR though.

**Comment by delucis** [comment]
Data seems solid to me! Looks very similar to previous runs, so I’m happy this is good.

@mandar1jn We filter out some sites when they produced bad data during the run, so I think the “rank” on the details table doesn’t take that into account.

@lloydjatkinson Do you think it would be possible to set up a monthly Azure job to run this for us instead of GH Actions?

**Comment by lloydjatkinson** [comment]
> @lloydjatkinson Do you think it would be possible to set up a monthly Azure job to run this for us instead of GH Actions?

This is definitely achievable! I ran this in a fairly good spec VM, I would need to automate creating and deleting the infrastructure and then running the benchmark on it, otherwise I'd be paying for a whole month of idle time. It could even be a GitHub Action that triggers said deployment, as one idea. But this is definitely a good idea to implement!

**Pull request merged**
