### PR TITLE
stats for september

### PR DESCRIPTION
**Pull request by lloydjatkinson**
Somehow it worked on the first try.

### CODE REVIEW

**Comment by lloydjatkinson** [comment]
Can we show the accessibility errors somehow? It's hard to figure out what counts, and the axe chrome extension doesn't find any anyway, so there must be different settings somewhere too.

**Comment by delucis** [comment]
Thanks @lloydjatkinson! Stats look good to me.

Re: the axe errors, it _might_ be due to version differences? Looks like this repo currently has `axe-core` 4.9.1 in the lock file, but the dev tools extension is on 4.10.0. We can try bumping up that version for the next run to see if that makes the difference.

**Comment by lloydjatkinson** [comment]
Looks like it hasn't deployed even though it was merged

**Comment by delucis** [comment]
Huh, you're right. Even though the preview in this PR worked fine. Let me take a look at Netlify.

**Comment by delucis** [comment]
The Netlify build had completed and then just hung without deploying... Retried now and it's deployed fine. Thanks for flagging!

**Pull request merged**
